Final version
arom4github/dictaverf pull request #1
Opened 2019-08-13 04:21 UTC by Gauthier1307

2019-08-16 04:46 UTC, arom4github commented
@Gauthier1307  Do I really need zip file? It's referred to your commit 'Add files via upload'

2019-08-16 04:57 UTC, arom4github requested changes

2019-08-16 04:57 UTC, arom4github commented on index.php
> +				<li class="nav-item"><a class="nav-link" href="helpj">помощь</a></li>
put the capital letter first "Помощь"

2019-08-16 04:57 UTC, arom4github commented on index.php
> +				<li class="nav-item mx-2"> <a class="nav-link" href="authorsj">вкладчики</a> </li>
It's better to say 'Авторы' (authors). 'Вкладчики' -  depositor, investor

2019-08-16 04:57 UTC, arom4github commented on index.php
> +  				<li class="nav-item mx-2"> <a class="nav-link" href="authors3">вкладчики</a> </li>
See my prev. comments

2019-08-16 04:57 UTC, arom4github commented on index.php
> +          <li class="nav-item mx-2"> <a class="nav-link" href="authors">вкладчики</a> </li>
See my prev. comments

2019-08-16 04:57 UTC, arom4github commented on index.php
> +            <li class="nav-item mx-2"> <a class="nav-link" href="aboutj1">О проекте</a> </li>
See my prev comments.

2019-08-16 04:57 UTC, arom4github commented on index.php
> +            <li class="nav-item mx-2"> <a class="nav-link" href="/fr"><span class="flag-icon flag-icon-fr"> </span></a></li>
Is it possible to have a config file to generate all those menus instead of copying them in the file? I see the same piece of code 4th times already

2019-08-16 05:00 UTC, arom4github commented
@Gauthier1307, how should I install your results on the production server?
should I unzip some file? It's not the right way!!
I should clone my repository, modify config file and that's all!

2019-08-16 06:06 UTC, Gauthier1307 commented
Hello,

I'm sorry about this pull request. Indeed, a zip file is useless in a git,
we never used git before and some features remain unclear to us.
 We are working on the report but we take into consideration all your
remarks and we will try to fix those problems.


Le ven. 16 août 2019 à 12:00, Alexey Romanenko <notifications@github.com> a
écrit :

> @Gauthier1307 <https://github.com/Gauthier1307>, how should I install
> your results on the production server?
> should I unzip some file? It's not the right way!!
> I should clone my repository, modify config file and that's all!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/arom4github/dictaverf/pull/1?email_source=notifications&email_token=AMIFMADI2FA72RSKWEBB5WLQEYX7BA5CNFSM4ILG6OE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4NVFGQ#issuecomment-521884314>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMIFMAA7ZPZD2SZ2NRSU3WLQEYX7BANCNFSM4ILG6OEQ>
> .
>

2019-09-24 06:58 UTC, arom4github commented
I'm closing this request

2019-09-24 07:00 UTC, merged